common:
  img_topic: "/hikrobot_camera/rgb"
  lid_topic: "/hesai/pandar"
  imu_topic: "/imu/data"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false
  
extrin_calib:
  extrinsic_T: [-0.055265, -0.00484, -0.05964]
  extrinsic_R: [-1, 0, 0, 0, -1, 0, 0, 0, 1]
  Rcl: [-0.0252327,-0.999163,0.0321841,
        0.0086208,-0.0324106,-0.999437,
        0.999644,-0.024941,0.00943139]

  Pcl: [0.0426121,-0.0398379,-0.0355619]
 #[0.000286199, -0.0594354,0.0042972]
  

  
time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 3
  filter_size_surf: 0.1
  lidar_type: 5 # xt32 LiDAR
  scan_line: 32
  blind: 0.5

vio:
  max_iterations: 3
  outlier_threshold: 100 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 2
  normal_en: false
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: false
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 3
  dept_err: 0.02
  beam_err: 0.01
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: true #false
  half_map_size: 100
  sliding_thresh: 100

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: true
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: 100
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
